style_edition = "2024"
edition = "2024"

# 统一管理宽度设置，但不包含 comment_width
max_width = 120
use_small_heuristics = "Max"
comment_width = 120
wrap_comments = true
normalize_comments = true

# 使多个标识符定义保持对齐风格，代码看上去可以非常工整
indent_style = "Block"
# 设置让自定义具有判别式的枚举体按等号对齐的宽度
enum_discrim_align_threshold = 10
# 设置让自定义具有判别式的枚举体按等号对齐的宽度
struct_field_align_threshold = 20
# 在match分支中，如果包含了块，也需要加逗号以示分隔
match_block_trailing_comma = true
# 结构体字段初始化时，自动使用同名变量
use_field_init_shorthand = true

# 自动将同一个 crate 的模块导入合并到一起
imports_granularity = "crate"
group_imports = "StdExternalCrate"

format_macro_matchers = true
force_explicit_abi = false
condense_wildcard_suffixes = true
merge_derives = false

# 指定 fmt 忽略的目录
ignore = ["src/test", "test", "docs"]
